# Generated by Django 3.1.8 on 2021-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0007_auto_20210426_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(upload_to='media/datasets'),
        ),
    ]
