# Generated by Django 3.1.8 on 2023-11-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0009_auto_20210426_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
