# Generated by Django 3.1.8 on 2021-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regressor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
