# Generated by Django 3.1.8 on 2021-04-23 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regressor', '0004_auto_20210422_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
