# Generated by Django 3.1.8 on 2021-04-26 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regressor', '0005_auto_20210422_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
    ]
